<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Remove</name>
   <tag></tag>
   <elementGuidId>52316c1c-060c-4b28-b552-4487d80fd1f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.delete</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ol[@id='mini-cart']/li/div/div/div[2]/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d62f731e-0623-41c6-8e83-f576325ce987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>140c2d62-8325-4690-a2de-22b3bfccec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {'data-cart-item': item_id, title: $t('Remove item')}</value>
      <webElementGuid>9f849c1e-4327-46a7-9bdd-9b2a4bba87f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action delete</value>
      <webElementGuid>126c9d17-c348-4b3e-89af-efef5f4ec81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart-item</name>
      <type>Main</type>
      <value>605049</value>
      <webElementGuid>74ed3868-e2ef-4c10-a21e-d7e7695f7be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Remove item</value>
      <webElementGuid>e116d514-7eee-4738-bb53-2ec15015c4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Remove
                    </value>
      <webElementGuid>ac28ba67-8a07-4baf-a17b-264653889538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mini-cart&quot;)/li[@class=&quot;item product product-item odd last&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product-item-details&quot;]/div[@class=&quot;product actions&quot;]/div[@class=&quot;secondary&quot;]/a[@class=&quot;action delete&quot;]</value>
      <webElementGuid>a538c146-87aa-436a-976a-b6aa7a2126b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='mini-cart']/li/div/div/div[2]/div[2]/a</value>
      <webElementGuid>78ac0fa5-ec4e-461a-a7d3-ad256d3272f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>afec6652-a838-4484-a0c3-c930e307f98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>2086a9d3-0389-491a-99d6-3b6348f1fb14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @title = 'Remove item' and (text() = '
                        Remove
                    ' or . = '
                        Remove
                    ')]</value>
      <webElementGuid>7c9772fa-0d3a-4ce4-b899-c273a2c8db1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
