<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shop New Yoga</name>
   <tag></tag>
   <elementGuidId>9fd15112-4eaf-4f31-8e8c-06c3d459ef5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[3]/div/a/span/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.action.more.button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7bdfb807-272c-4951-99a8-5bd8720471e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action more button</value>
      <webElementGuid>ca650442-d774-4e11-9162-e1c589934f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shop New Yoga</value>
      <webElementGuid>026da9b9-e1d3-43b3-9adc-e1b9efb65cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;blocks-promo&quot;]/a[@class=&quot;block-promo home-main&quot;]/span[@class=&quot;content bg-white&quot;]/span[@class=&quot;action more button&quot;]</value>
      <webElementGuid>1e550eda-7de4-493c-953d-f5730001d46e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[3]/div/a/span/span[2]</value>
      <webElementGuid>b727c243-2a63-45f7-9a6c-2e6e504f1097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/span/span[2]</value>
      <webElementGuid>f48bd764-9fbd-45dd-bca9-e5fa5e6e9511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Shop New Yoga' or . = 'Shop New Yoga')]</value>
      <webElementGuid>afef5d06-9d81-4a02-8533-a2bad04e78a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
