<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Phoebe Zipper Sweatshirt</name>
   <tag></tag>
   <elementGuidId>c3f22593-3b29-4dd1-a747-ddf5d4371f4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[4]/div/div[2]/div[3]/div/div/ol/li/div/div/strong/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.product-item-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>932c1739-7516-49ad-943e-57081ef1c675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Phoebe Zipper Sweatshirt</value>
      <webElementGuid>bd5791b5-74ce-4b54-9454-17fd3972b159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/phoebe-zipper-sweatshirt.html</value>
      <webElementGuid>1855827b-d5c1-4207-aebd-dba1416ca2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item-link</value>
      <webElementGuid>19c6b47e-bddf-4e7b-9b5c-ee49de953434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Phoebe Zipper Sweatshirt </value>
      <webElementGuid>c6159f84-4f80-45b3-822a-6b2dbeeb5a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;block widget block-products-list grid&quot;]/div[@class=&quot;block-content&quot;]/div[@class=&quot;products-grid grid&quot;]/ol[@class=&quot;product-items widget-product-grid&quot;]/li[@class=&quot;product-item&quot;]/div[@class=&quot;product-item-info&quot;]/div[@class=&quot;product-item-details&quot;]/strong[@class=&quot;product-item-name&quot;]/a[@class=&quot;product-item-link&quot;]</value>
      <webElementGuid>256f7019-186e-4916-9dab-6eafdbbc3e66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[4]/div/div[2]/div[3]/div/div/ol/li/div/div/strong/a</value>
      <webElementGuid>6fcb14e3-0406-4e7f-8ef1-cd5dd43745c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Phoebe Zipper Sweatshirt')]</value>
      <webElementGuid>98a5a413-1253-4ee8-9a6f-a1232158fcdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://magento.softwaretestingboard.com/phoebe-zipper-sweatshirt.html')])[2]</value>
      <webElementGuid>20173346-20af-4e9f-99c4-0308f583cef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong/a</value>
      <webElementGuid>195da675-4b91-4df5-b949-3a2f2ec840a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Phoebe Zipper Sweatshirt' and @href = 'https://magento.softwaretestingboard.com/phoebe-zipper-sweatshirt.html' and (text() = '
Phoebe Zipper Sweatshirt ' or . = '
Phoebe Zipper Sweatshirt ')]</value>
      <webElementGuid>44823153-8dd4-4dcc-b231-531d24bedf38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
