<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Add to Cart</name>
   <tag></tag>
   <elementGuidId>a790abc2-9c76-45c6-81c2-7d2a82f4d045</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>480e1432-7019-4237-8524-776f9b282bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>321e7453-4d9d-4b44-8995-e415eb0af04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)/span[1]</value>
      <webElementGuid>0b7f6df8-b67a-44c0-a40d-803247addc35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']/span</value>
      <webElementGuid>26d1be11-2300-471e-9a66-b8dc9788c4fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/button/span</value>
      <webElementGuid>d99594f1-c9ee-4a5e-94d1-8f0083d6e2ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Add to Cart' or . = 'Add to Cart')]</value>
      <webElementGuid>1ec4e5ba-6b00-41ef-834b-7b3b7ca5d49f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
