<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Product_product-item-photo</name>
   <tag></tag>
   <elementGuidId>bbc6e7f7-1c03-431c-9e3c-5d1970b4d36f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.product-item-photo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='product-comparison']/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1173a90-6d06-4b7a-9c13-2f685b53a387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-item-photo</value>
      <webElementGuid>d78770b6-aa93-4649-9e57-b2965039740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/gabrielle-micro-sleeve-top.html</value>
      <webElementGuid>8237b11e-ab03-4157-b3e8-5e6efad40064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gabrielle Micro Sleeve Top</value>
      <webElementGuid>e3478da3-4d36-4997-9cf8-8dca2dc67607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-comparison&quot;)/tbody[1]/tr[1]/td[@class=&quot;cell product info&quot;]/a[@class=&quot;product-item-photo&quot;]</value>
      <webElementGuid>521660c6-3af7-4fce-ba6c-f54239a5ab23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='product-comparison']/tbody/tr/td/a</value>
      <webElementGuid>0efc114c-0046-4bd0-9b23-92be4d370604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://magento.softwaretestingboard.com/gabrielle-micro-sleeve-top.html')]</value>
      <webElementGuid>0cf840a5-acb9-4a14-9030-497f67ea8196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/td/a</value>
      <webElementGuid>c6b25d0c-08e2-43f8-8ef6-2532e8b4828b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/gabrielle-micro-sleeve-top.html' and @title = 'Gabrielle Micro Sleeve Top']</value>
      <webElementGuid>1553aabb-1946-444e-bbe9-e748a25bef58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
