<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>message_email-error</name>
   <tag></tag>
   <elementGuidId>49badb63-c03f-459e-be27-c3aeb2ec10c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='email-error']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email-error</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b35190a8-a3a4-4bb0-936a-444a53afbfc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>99d72b5b-6c45-4eb7-a249-f0b84faa1542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>90e3c1fc-2364-482b-a4fc-788bc5b0b941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>b089e4c6-49a4-473f-9832-ac34d3e42c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-error</value>
      <webElementGuid>1302ce0d-1378-45c4-ab0d-a1a0a7f68349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a valid email address (Ex: johndoe@domain.com).</value>
      <webElementGuid>5f7cec5a-b700-40da-ac73-2ebc6253bf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-error&quot;)</value>
      <webElementGuid>02ad326b-e2e3-4e99-bd8a-609e0e8e35c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='email-error']</value>
      <webElementGuid>b49526ad-709c-4039-bd81-1d86de5fc110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/fieldset/div[2]/div/div</value>
      <webElementGuid>8fb1b55c-69f4-43fb-a285-c60a873d35b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div</value>
      <webElementGuid>cf9ee4e1-8c98-495b-8d1f-28d9a9160eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'email-error' and (text() = 'Please enter a valid email address (Ex: johndoe@domain.com).' or . = 'Please enter a valid email address (Ex: johndoe@domain.com).')]</value>
      <webElementGuid>7b5881d0-825c-4571-96a5-9792fdf927dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
