<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Almost finished. We need to confirm you_aebf89</name>
   <tag></tag>
   <elementGuidId>05a1763f-367e-4545-b29f-b1f75c343f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mce-success-response</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mce-success-response']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e605da41-a951-475a-9369-fbb9c0f0e744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>response</value>
      <webElementGuid>cb9dea62-e42b-4b4a-8f63-d16fd984867f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mce-success-response</value>
      <webElementGuid>b459f7cb-de8c-4b68-a002-f0b88a4219e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Almost finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you.</value>
      <webElementGuid>3613092c-2d5f-44f4-b2d9-9b52a77ce06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mce-success-response&quot;)</value>
      <webElementGuid>b3d41625-4121-48b2-9d82-6eff8eb48311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='mce-success-response']</value>
      <webElementGuid>711dcc10-c0ae-4181-86d7-aeda8e465f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mce-responses']/div[2]</value>
      <webElementGuid>9fd2cf9a-10ee-4426-99e9-57234faa34c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]</value>
      <webElementGuid>bf134268-a363-46c4-9ba1-9a657318fedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'mce-success-response' and (text() = 'Almost finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you.' or . = 'Almost finished... We need to confirm your email address. To complete the subscription process, please click the link in the email we just sent you.')]</value>
      <webElementGuid>9b8df612-eaad-407b-9e4e-0daf413d09fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
