<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Position_subscribe</name>
   <tag></tag>
   <elementGuidId>4b615f2c-b13d-4c1a-b80e-056e376a08b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mc-embedded-subscribe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mc-embedded-subscribe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad608e66-37c8-4b53-a292-d96ae6b5ce87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c79a97f-ea10-4c60-b628-6f1dba6b5357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Subscribe</value>
      <webElementGuid>2e4aa617-8488-4b56-ac27-2ab5141d12d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscribe</value>
      <webElementGuid>e05c2eee-af52-4585-b822-b6eba4821598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mc-embedded-subscribe</value>
      <webElementGuid>5699b244-32c8-476e-9197-b7f9f2595935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0465c50c-3a1f-4cb6-b891-f13860e3223b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mc-embedded-subscribe&quot;)</value>
      <webElementGuid>028a9684-93b8-44a6-8ecd-f4a9aba5ccc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mc-embedded-subscribe']</value>
      <webElementGuid>9868d309-5a3b-4f87-a0fc-4859953748ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mc_embed_signup_scroll']/div[9]/input</value>
      <webElementGuid>ba8ca89d-8191-4d18-8970-2d05043e6093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/input</value>
      <webElementGuid>1bc7f141-bd0c-4361-a3a9-3205af1a3bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'subscribe' and @id = 'mc-embedded-subscribe']</value>
      <webElementGuid>eb90a49c-5602-4ca2-8ad5-fbabfb71a437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
