<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to Cart</name>
   <tag></tag>
   <elementGuidId>1c5036a7-ee85-48c3-adef-063431f5facc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d591af30-6626-4502-b727-7c75be9c054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4399da8c-5c5a-4f25-83da-2008deee2ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add to Cart</value>
      <webElementGuid>718765fe-6358-4a67-b0be-397876976a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action primary tocart</value>
      <webElementGuid>ef422d86-aad3-4c95-9cbb-9d25e3023c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-addtocart-button</value>
      <webElementGuid>d8297450-ff2a-45e1-8be8-026be508df79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Add to Cart
</value>
      <webElementGuid>ec754f1f-afed-4225-a482-8eb3cc97e61d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)</value>
      <webElementGuid>612aae6b-12ff-4648-9efb-62b913e53c5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']</value>
      <webElementGuid>ecad19fc-cda6-4bc3-80ba-54f41de2eb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div/div/div[2]/button</value>
      <webElementGuid>f510be8f-e23f-4be8-b903-8f459298c369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/button</value>
      <webElementGuid>8fa6f352-dcb6-4d70-abe0-a56273495144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Add to Cart' and @id = 'product-addtocart-button' and (text() = '
Add to Cart
' or . = '
Add to Cart
')]</value>
      <webElementGuid>db17483e-f75f-4508-8cd1-4f72c4395148</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
