<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Bottle6</name>
   <tag></tag>
   <elementGuidId>cb59ed47-1ec4-4b7b-b990-bcd83520ce82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qs-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='qs-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>74757d24-cacf-4027-998e-ce5347875026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>feae237a-d3a7-4cb7-8448-22321c5e7749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qs-option-0</value>
      <webElementGuid>13cedf07-e1fc-4b9b-9d5a-148d4a4ae972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2fdb2260-4637-4194-bfa3-fed081a79b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Bottle6</value>
      <webElementGuid>67187052-258d-409e-b6c4-13529a724138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qs-option-0&quot;)</value>
      <webElementGuid>0a1a18dd-7ca2-437b-81b0-37d6c8d39ef0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='qs-option-0']</value>
      <webElementGuid>e4c361c1-06a1-467c-8650-d235821fe589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search_autocomplete']/ul/li</value>
      <webElementGuid>363208e5-5515-462e-b469-269d120ece94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/ul/li</value>
      <webElementGuid>510fe4a6-9110-4417-9f44-0096cd106792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'qs-option-0' and (text() = ' Bottle6' or . = ' Bottle6')]</value>
      <webElementGuid>ebed6501-9dc7-4aeb-bcd8-550b5cf9caff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
